### ISSUE TITLE
Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead.

### ISSUE THREAD

**Issue by creage** [lodash/lodash-webpack-plugin#174] opened 2020-10-12 14:17 UTC
This plugin is not compatible with latest Webpack anymore (v5), as it has some API changes. 

Please see details here https://github.com/webpack/webpack/issues/11647

**Comment by spnc-omz** [comment] 2020-10-12 18:48
same as: https://github.com/lodash/lodash-webpack-plugin/issues/167 ?

**Comment by TomFoyster** [comment] 2020-10-14 16:10
This line needs to be removed for v5 support;

https://github.com/lodash/lodash-webpack-plugin/blob/master/src/index.js#L45

I replaced it with the below to try and support <5.1.0 too;
```
/* Support for Webpack >= 5.1.0 */
if(!compiler.webpack) {
    return data
}
```

(`compiler.webpack` was only added in `5.1.0`) 

This works in my App but I can't check tests pass as they fail with version 5 it seems.

**Comment by bnjmnt4n** [comment] 2020-12-19 18:06
Marking this as a duplicate of #167.

**Closed by bnjmnt4n** 2020-12-19 18:06 UTC
Labels: duplicate
